### PR TITLE
Add Flycast Standalone

### PR DESCRIPTION
**Pull request by WingofaGriffin**
[x] Controller Config
[x] SRM Scraper
[x] Shell Script
[x] Saves, States, Bios
[x] Widescreen Hack
[ ] Hotkeys

Set to 2x up-scaling, and mostly everything else is the same. Needs a custom controller map on steam as they do not allow multi-button commands.

### CODE REVIEW

**Comment by Godsbane** [comment]
prob holding this til after next release cycle

**Comment by WingofaGriffin** [comment]
@rawdatafeel claims they have tested it and it works fine with no controller config, as the menu is brought up via tab/select

**Comment by Godsbane** [comment]
fixed the merge - do you want to look at the appimage over the flatpak since there's a new release?

**Comment by WingofaGriffin** [comment]
Screenshot_20230227_232119_Discord
Lead dev says both are fine. Happy to move to appimage still, but keeping it flatpak is probably less hassle.

**Comment by Godsbane** [comment]
Ok great

**Pull request merged**
