### PR TITLE
Cemu Flatpak Number 2 Electric Boogaloo

### PR DESCRIPTION
**Pull request by Witherking25**
make it use `--user` when adding my repository so that people don't need to set a password

### CODE REVIEW

**Comment by popsUlfr** [comment]
Please add a zenity prompt asking the user permission to add the flatpak repo.

**Comment by Witherking25** [comment]
Uh, oh

**Comment by Witherking25** [comment]
zenity prompt added

**Comment by Witherking25** [comment]
I believe its ready

**Comment by popsUlfr** [comment]
You should really squash your commits into one and rebase upon the latest dev branch. You seem to be carrying a lot of retroarch stuff that has nothing to do with the pull request.

**Pull request merged**
