### PR TITLE
Set DOSBox-Pure and PCSX2 as the default emulators for DOS and PS2 in ES-DE

### PR DESCRIPTION
**Pull request by AngelofWoe**

### CODE REVIEW

**Comment by AngelofWoe** [comment]
Due to requests, added PCSX2 Standalone and melonDS for NDS.

**Comment by AngelofWoe** [comment]
Sidenote: We may want to actually switch both to DeSuMe - melonDS requires BIOS files while DeSuMe does not.

**Comment by Godsbane** [comment]
@dragoonDorise is there a preference on which (melonDS vs desmume) core you want as default?

**Comment by dragoonDorise** [comment]
Hi @AngelofWoe & @Godsbane , the best option would be melonDS Standalone as you can apply graphics enhancements but I could get melonDS to load games from SRM or ESDE. I tested both cores for DS and I ended up using melonDS so let's keep melonDS at least for now.

**Pull request merged**
