### PR TITLE
[cxbx-reloaded] Add support for the original xbox emulator Cxbx-Reloaded

### PR DESCRIPTION
**Pull request by popsUlfr**
~~More feature complete, easier to set up and efficient than xemu.~~
A feature rich, efficient and easy to set up original xbox emulator:
- https://github.com/Cxbx-Reloaded/Cxbx-Reloaded

* A Bottle is set up (com.usebottles.bottles) to run it because Proton is erroring out when launching a game
* Automatically downloads the latest release if there is one
* Integrates into EmulationStation
* Steam Deck input binding functional

Note: Cxbx-Reloaded has an exclusive fullscreen option but it does bad things (resetting the desktop res and the rotation) on the deck and is not needed for fullscreen when launched in Game Mode.

Useful Hotkeys:
- ESC/Alt+F4: Close emulation
- F5: Start emulating
- F6: Stop emulating
- F9: Toggle framerate unlock hack
- F10/ALT+ENTER: Toggle fake windowed fullscreen
- F11: Switch between normal, wireframe, point graphics

*Jet Set Radio Future*

### CODE REVIEW

**Comment by dragoonDorise** [comment]
Hi, great pull request, can you please do it on the dev branch so I can test everything? Thanks!

**Comment by popsUlfr** [comment]
> Hi, great pull request, can you please do it on the dev branch so I can test everything? Thanks!

Thank you for your kind words!

By "do it on the dev branch" do you mean you want me to rebase the changes against your dev branch ?

**Comment by dragoonDorise** [comment]
Hi, I had to revert the pull request, in order to do your installation an user has to type its password, regular users won't know how to do that, I want EmuDeck to be as user friendly as possible, I'm thinking about making an "expert mode" so power users can make use of your work, I'm making a review of all my pending PR, would you mind reapplying your code when I create that expert mode?

**Comment by popsUlfr** [comment]
> in order to do your installation an user has to type its password

A password ? At which point ? :confused:

**Comment by dragoonDorise** [comment]
I'm sorry, I don't remember, I've had several PR with the same issue, can't remember when did your script asked for a password. But the flatpak override line looks like it might be the culprit

**Comment by popsUlfr** [comment]
> I'm sorry, I don't remember, I've had several PR with the same issue, can't remember when did your script asked for a password. But the flatpak override line looks like it could be the culprit

I rechecked on my Steam Deck and on a fresh SteamOS image and I can not reproduce.
The flatpak override is called with the `--user` switch so it wouldn't ask the user for a password.

There might be something wrong on your system or configuration but there shouldn't be any password prompt.

**Comment by dragoonDorise** [comment]
weird, I'll try it again!

**Comment by popsUlfr** [comment]
I think it's a mix up with #32 , it tries to add a custom repo which requires a password without the `--user` flag. But like they said, simply add `--user` to the flatpak command to make the change only locally for the current user.

**Pull request merged**
