### PR TITLE
prelim mame proton custom system

### PR DESCRIPTION
**Pull request by Godsbane**
custom system

### CODE REVIEW

**Comment by AchillesPDX** [comment]
\Emulation\tools\launchers\mame-proton.sh
```
#!/bin/sh
## Config
# App Path
APPPATH="/run/media/mmcblk0p1/Emulation/tools/MAME"
# Steam Path
STEAMPATH="${HOME}/.local/share/Steam"
# Proton Path
PROTON="${STEAMPATH}/steamapps/common/Proton 7.0/proton"
# Prefix
PFX="${STEAMPATH}/steamapps/compatdata/pfx"
# AppID
APPID=0

# Set environment variables
set_env() {
    # Set default data path if it isn't set, then include an appID
    if [ -z ${STEAM_COMPAT_DATA_PATH+x} ]; then
        export STEAM_COMPAT_DATA_PATH="${PFX}"/${SteamAppId:-${APPID}}
    elif ! [ ${SteamGameId} -ge 0 ] 2>/dev/null && ! [ ${SteamAppId} -ge 0 ] 2>/dev/null && ! [ $(basename ${STEAM_COMPAT_DATA_PATH}) -ge 0 ] 2>/dev/null; then
        export SteamAppId=${APPID}
    fi
    # Set default Steam Client path if it isn't
    if [ -z ${STEAM_COMPAT_CLIENT_INSTALL_PATH+x} ]; then
        export STEAM_COMPAT_CLIENT_INSTALL_PATH="${STEAMPATH}"
    fi
    # Create prefix if it doesn't exist
    if ! [ -d ${STEAM_COMPAT_DATA_PATH} ]; then
        install -d ${STEAM_COMPAT_DATA_PATH} || exit 1
    fi
}

# Main
set_env
cd ${APPPATH}
python "${PROTON}" waitforexitandrun "${APPPATH}/mame.exe" "${@}"
```
\home\.emulationstation\custom_systems\es_systems.xml
```
<?xml version="1.0"?>
<systemList>
    <system>
        <name>wiiu</name>
        <fullname>Nintendo Wii U</fullname>
        <path>%ROMPATH%/wiiu/roms</path>
        <extension>.rpx .RPX .wud .WUD .wux .WUX .elf .ELF .iso .ISO .wad .WAD .wua .WUA</extension>
        <command label="Cemu (Proton)">/usr/bin/bash /run/media/mmcblk0p1/Emulation/tools/launchers/cemu.sh -f -g z:%ROM%</command>
        <platform>wiiu</platform>
        <theme>wiiu</theme>
    </system>
    <system>
        <name>arcade</name>
        <fullname>Arcade</fullname>
        <path>%ROMPATH%/arcade</path>
        <extension>.cmd .CMD .7z .7Z .zip .ZIP</extension>
        <command label="MAME - Current">%EMULATOR_RETROARCH% -L %CORE_RETROARCH%/mame_libretro.so %ROM%</command>
        <command label="MAME 2010">%EMULATOR_RETROARCH% -L %CORE_RETROARCH%/mame2010_libretro.so %ROM%</command>
        <command label="MAME 2003-Plus">%EMULATOR_RETROARCH% -L %CORE_RETROARCH%/mame2003_plus_libretro.so %ROM%</command>
        <command label="MAME 2000">%EMULATOR_RETROARCH% -L %CORE_RETROARCH%/mame2000_libretro.so %ROM%</command>
        <command label="MAME (Standalone)">%STARTDIR%=~/.mame %EMULATOR_MAME% -rompath %ROMPATH%/arcade %BASENAME%</command>
        <command label="MAME (Proton)">/usr/bin/bash /run/media/mmcblk0p1/Emulation/tools/launchers/mame-proton.sh -rompath %ROMPATH%/arcade %BASENAME%</command>
        <command label="FinalBurn Neo">%EMULATOR_RETROARCH% -L %CORE_RETROARCH%/fbneo_libretro.so %ROM%</command>
        <command label="FB Alpha 2012">%EMULATOR_RETROARCH% -L %CORE_RETROARCH%/fbalpha2012_libretro.so %ROM%</command>
        <command label="Flycast">%EMULATOR_RETROARCH% -L %CORE_RETROARCH%/flycast_libretro.so %ROM%</command>
        <command label="Flycast (Standalone)">%EMULATOR_FLYCAST% %ROM%</command>
        <platform>arcade</platform>
        <theme>arcade</theme>
    </system>
</systemList>
```

Mame configs to follow

**Comment by AchillesPDX** [comment]
The latest 64 bit Mame for windows was downloaded from here and extracted to /Emulation/tools/MAME
https://www.mamedev.org/release.html

/Emulation/tools/MAME/cfg/default.cfg
```
<?xml version="1.0"?>
<!-- This file is autogenerated; comments and unknown tags will be stripped -->
<mameconfig version="10">
    <system name="default">
        <input>
            <port type="P1_JOYSTICK_UP">
                <newseq type="standard">
                    JOYCODE_1_DPADUP OR JOYCODE_1_YAXIS_UP_SWITCH OR KEYCODE_UP
                </newseq>
            </port>
            <port type="P1_JOYSTICK_DOWN">
                <newseq type="standard">
                    JOYCODE_1_DPADDOWN OR JOYCODE_1_YAXIS_DOWN_SWITCH OR KEYCODE_UP
                </newseq>
            </port>
            <port type="P1_JOYSTICK_LEFT">
                <newseq type="standard">
                    JOYCODE_1_DPADLEFT OR JOYCODE_1_XAXIS_LEFT_SWITCH OR KEYCODE_LEFT
                </newseq>
            </port>
            <port type="P1_JOYSTICK_RIGHT">
                <newseq type="standard">
                    JOYCODE_1_DPADRIGHT OR JOYCODE_1_XAXIS_RIGHT_SWITCH OR KEYCODE_RIGHT
                </newseq>
            </port>
            <port type="P1_BUTTON1">
                <newseq type="standard">
                    JOYCODE_1_BUTTON3
                </newseq>
            </port>
            <port type="P1_BUTTON2">
                <newseq type="standard">
                    JOYCODE_1_BUTTON1
                </newseq>
            </port>
            <port type="P1_BUTTON3">
                <newseq type="standard">
                    JOYCODE_1_BUTTON2
                </newseq>
            </port>
            <port type="P1_BUTTON4">
                <newseq type="standard">
                    JOYCODE_1_BUTTON4
                </newseq>
            </port>
            <port type="P1_START">
                <newseq type="standard">
                    JOYCODE_1_BUTTON7 OR KEYCODE_1
                </newseq>
            </port>
            <port type="P1_SELECT">
                <newseq type="standard">
                    JOYCODE_1_BUTTON8 OR KEYCODE_5
                </newseq>
            </port>
            <port type="START1">
                <newseq type="standard">
                    KEYCODE_1 OR JOYCODE_1_BUTTON7
                </newseq>
            </port>
            <port type="COIN1">
                <newseq type="standard">
                    KEYCODE_5 OR JOYCODE_1_BUTTON8
                </newseq>
            </port>
            <port type="SERVICE">
                <newseq type="standard">
                    KEYCODE_F2 OR JOYCODE_1_BUTTON8 JOYCODE_1_BUTTON10
                </newseq>
            </port>
            <port type="UI_ON_SCREEN_DISPLAY">
                <newseq type="standard">
                    JOYCODE_1_BUTTON8 JOYCODE_1_BUTTON9
                </newseq>
            </port>
            <port type="UI_CONFIGURE">
                <newseq type="standard">
                    JOYCODE_1_BUTTON9 JOYCODE_1_BUTTON10
                </newseq>
            </port>
            <port type="UI_PAUSE">
                <newseq type="standard">
                    JOYCODE_1_BUTTON8 JOYCODE_1_BUTTON1
                </newseq>
            </port>
            <port type="UI_THROTTLE">
                <newseq type="standard">
                    JOYCODE_1_BUTTON8 JOYCODE_1_ZAXIS_NEG_SWITCH
                </newseq>
            </port>
            <port type="UI_SHOW_FPS">
                <newseq type="standard">
                    JOYCODE_1_BUTTON8 JOYCODE_1_BUTTON4
                </newseq>
            </port>
            <port type="UI_UP">
                <newseq type="standard">
                    KEYCODE_UP OR JOYCODE_1_YAXIS_UP_SWITCH OR JOYCODE_1_DPADUP
                </newseq>
            </port>
            <port type="UI_DOWN">
                <newseq type="standard">
                    KEYCODE_DOWN OR JOYCODE_1_YAXIS_DOWN_SWITCH OR JOYCODE_1_DPADDOWN
                </newseq>
            </port>
            <port type="UI_LEFT">
                <newseq type="standard">
                    KEYCODE_LEFT OR JOYCODE_1_XAXIS_LEFT_SWITCH OR JOYCODE_1_DPADLEFT
                </newseq>
            </port>
            <port type="UI_RIGHT">
                <newseq type="standard">
                    KEYCODE_RIGHT OR JOYCODE_1_XAXIS_RIGHT_SWITCH OR JOYCODE_1_DPADRIGHT
                </newseq>
            </port>
            <port type="UI_HOME">
                <newseq type="standard">
                    KEYCODE_HOME OR JOYCODE_1_RZAXIS_NEG_SWITCH
                </newseq>
            </port>
            <port type="UI_END">
                <newseq type="standard">
                    KEYCODE_END OR JOYCODE_1_ZAXIS_NEG_SWITCH
                </newseq>
            </port>
            <port type="UI_PAGE_UP">
                <newseq type="standard">
                    KEYCODE_PGUP OR JOYCODE_1_BUTTON5
                </newseq>
            </port>
            <port type="UI_PAGE_DOWN">
                <newseq type="standard">
                    KEYCODE_PGDN OR JOYCODE_1_BUTTON6
                </newseq>
            </port>
            <port type="UI_CANCEL">
                <newseq type="standard">
                    JOYCODE_1_BUTTON8 JOYCODE_1_BUTTON7 OR KEYCODE_ESC
                </newseq>
            </port>
            <port type="UI_CLEAR">
                <newseq type="standard">
                    JOYCODE_1_BUTTON3
                </newseq>
            </port>
            <port type="UI_SAVE_STATE">
                <newseq type="standard">
                    JOYCODE_1_BUTTON8 JOYCODE_1_BUTTON6
                </newseq>
            </port>
            <port type="UI_LOAD_STATE">
                <newseq type="standard">
                    JOYCODE_1_BUTTON8 JOYCODE_1_BUTTON5
                </newseq>
            </port>
        </input>
    </system>
</mameconfig>
```

/Emulation/tools/MAME/mame.ini
```
#
# CORE CONFIGURATION OPTIONS
#
readconfig                1
writeconfig               0

#
# CORE SEARCH PATH OPTIONS
#
homepath                  .
rompath                   roms
hashpath                  hash
samplepath                samples
artpath                   artwork
ctrlrpath                 ctrlr
inipath                   .;ini;ini/presets
fontpath                  .
cheatpath                 cheat
crosshairpath             crosshair
pluginspath               plugins
languagepath              language
swpath                    software

#
# CORE OUTPUT DIRECTORY OPTIONS
#
cfg_directory             cfg
nvram_directory           nvram
input_directory           inp
state_directory           sta
snapshot_directory        snap
diff_directory            diff
comment_directory         comments
share_directory           share

#
# CORE STATE/PLAYBACK OPTIONS
#
state                     
autosave                  0
rewind                    0
rewind_capacity           100
playback                  
record                    
exit_after_playback       0
mngwrite                  
aviwrite                  
wavwrite                  
snapname                  %g/%i
snapsize                  auto
snapview                  auto
snapbilinear              1
statename                 %g
burnin                    0

#
# CORE PERFORMANCE OPTIONS
#
autoframeskip             0
frameskip                 0
seconds_to_run            0
throttle                  1
sleep                     1
speed                     1.0
refreshspeed              0
lowlatency                1

#
# CORE RENDER OPTIONS
#
keepaspect                1
unevenstretch             1
unevenstretchx            0
unevenstretchy            0
autostretchxy             0
intoverscan               0
intscalex                 0
intscaley                 0

#
# CORE ROTATION OPTIONS
#
rotate                    1
ror                       0
rol                       0
autoror                   0
autorol                   0
flipx                     0
flipy                     0

#
# CORE ARTWORK OPTIONS
#
artwork_crop              0
fallback_artwork          
override_artwork          

#
# CORE SCREEN OPTIONS
#
brightness                1.0
contrast                  1.0
gamma                     1.0
pause_brightness          0.65
effect                    none

#
# CORE VECTOR OPTIONS
#
beam_width_min            1.0
beam_width_max            1.0
beam_dot_size             1.0
beam_intensity_weight     0
flicker                   0

#
# CORE SOUND OPTIONS
#
samplerate                48000
samples                   1
volume                    0
compressor                1
speaker_report            0

#
# CORE INPUT OPTIONS
#
coin_lockout              1
ctrlr                     
mouse                     1
joystick                  1
lightgun                  0
multikeyboard             0
multimouse                0
steadykey                 0
ui_active                 0
offscreen_reload          0
joystick_map              auto
joystick_deadzone         0.9
joystick_saturation       0.85
natural                   0
joystick_contradictory    0
coin_impulse              0

#
# CORE INPUT AUTOMATIC ENABLE OPTIONS
#
paddle_device             keyboard
adstick_device            keyboard
pedal_device              joystick
dial_device               keyboard
trackball_device          mouse
lightgun_device           keyboard
positional_device         keyboard
mouse_device              mouse

#
# CORE DEBUGGING OPTIONS
#
verbose                   0
log                       0
oslog                     0
debug                     0
update_in_pause           0
debugscript               
debuglog                  0

#
# CORE COMM OPTIONS
#
comm_localhost            0.0.0.0
comm_localport            15112
comm_remotehost           127.0.0.1
comm_remoteport           15112
comm_framesync            0

#
# CORE MISC OPTIONS
#
drc                       1
drc_use_c                 0
drc_log_uml               0
drc_log_native            0
bios                      
cheat                     0
skip_gameinfo             1
uifont                    default
ui                        cabinet
ramsize                   
confirm_quit              0
ui_mouse                  1
language                  
nvram_save                1

#
# SCRIPTING OPTIONS
#
autoboot_command          
autoboot_delay            0
autoboot_script           
console                   0
plugins                   1
plugin                    
noplugin                  

#
# HTTP SERVER OPTIONS
#
http                      0
http_port                 8080
http_root                 web

#
# OSD KEYBOARD MAPPING OPTIONS
#
uimodekey                 SCRLOCK

#
# OSD FONT OPTIONS
#
uifontprovider            auto

#
# OSD OUTPUT OPTIONS
#
output                    auto

#
# OSD INPUT OPTIONS
#
keyboardprovider          auto
mouseprovider             auto
lightgunprovider          auto
joystickprovider          auto

#
# OSD DEBUGGING OPTIONS
#
debugger                  auto
debugger_port             23946
debugger_font             auto
debugger_font_size        0
watchdog                  0

#
# OSD PERFORMANCE OPTIONS
#
numprocessors             auto
bench                     0

#
# OSD VIDEO OPTIONS
#
video                     auto
numscreens                1
window                    0
maximize                  1
waitvsync                 0
syncrefresh               0
monitorprovider           auto

#
# OSD PER-WINDOW VIDEO OPTIONS
#
screen                    auto
aspect                    auto
resolution                auto
view                      auto
screen0                   auto
aspect0                   auto
resolution0               auto
view0                     auto
screen1                   auto
aspect1                   auto
resolution1               auto
view1                     auto
screen2                   auto
aspect2                   auto
resolution2               auto
view2                     auto
screen3                   auto
aspect3                   auto
resolution3               auto
view3                     auto

#
# OSD FULL SCREEN OPTIONS
#
switchres                 0

#
# OSD ACCELERATED VIDEO OPTIONS
#
filter                    1
prescale                  4

#
# OpenGL-SPECIFIC OPTIONS
#
gl_forcepow2texture       0
gl_notexturerect          0
gl_vbo                    1
gl_pbo                    1
gl_glsl                   0
gl_glsl_filter            1
glsl_shader_mame0         none
glsl_shader_mame1         none
glsl_shader_mame2         none
glsl_shader_mame3         none
glsl_shader_mame4         none
glsl_shader_mame5         none
glsl_shader_mame6         none
glsl_shader_mame7         none
glsl_shader_mame8         none
glsl_shader_mame9         none
glsl_shader_screen0       none
glsl_shader_screen1       none
glsl_shader_screen2       none
glsl_shader_screen3       none
glsl_shader_screen4       none
glsl_shader_screen5       none
glsl_shader_screen6       none
glsl_shader_screen7       none
glsl_shader_screen8       none
glsl_shader_screen9       none

#
# OSD SOUND OPTIONS
#
sound                     auto
audio_latency             2

#
# PORTAUDIO OPTIONS
#
pa_api                    none
pa_device                 none
pa_latency                0

#
# BGFX POST-PROCESSING OPTIONS
#
bgfx_path                 bgfx
bgfx_backend              auto
bgfx_debug                0
bgfx_screen_chains        default
bgfx_shadow_mask          slot-mask.png
bgfx_lut                  lut-default.png
bgfx_avi_name             auto

#
# WINDOWS PERFORMANCE OPTIONS
#
priority                  0
profile                   0

#
# WINDOWS VIDEO OPTIONS
#
menu                      0
attach_window             

#
# DIRECT3D POST-PROCESSING OPTIONS
#
hlslpath                  hlsl
hlsl_enable               0
hlsl_oversampling         0
hlsl_write                auto
hlsl_snap_width           2048
hlsl_snap_height          1536
shadow_mask_tile_mode     0
shadow_mask_alpha         0.0
shadow_mask_texture       shadow-mask.png
shadow_mask_x_count       6
shadow_mask_y_count       4
shadow_mask_usize         0.1875
shadow_mask_vsize         0.25
shadow_mask_uoffset       0.0
shadow_mask_voffset       0.0
distortion                0.0
cubic_distortion          0.0
distort_corner            0.0
round_corner              0.0
smooth_border             0.0
reflection                0.0
vignetting                0.0
scanline_alpha            0.0
scanline_size             1.0
scanline_height           1.0
scanline_variation        1.0
scanline_bright_scale     1.0
scanline_bright_offset    0.0
scanline_jitter           0.0
hum_bar_alpha             0.0
defocus                   0.0,0.0
converge_x                0.0,0.0,0.0
converge_y                0.0,0.0,0.0
radial_converge_x         0.0,0.0,0.0
radial_converge_y         0.0,0.0,0.0
red_ratio                 1.0,0.0,0.0
grn_ratio                 0.0,1.0,0.0
blu_ratio                 0.0,0.0,1.0
saturation                1.0
offset                    0.0,0.0,0.0
scale                     1.0,1.0,1.0
power                     1.0,1.0,1.0
floor                     0.0,0.0,0.0
phosphor_life             0.0,0.0,0.0
chroma_mode               3
chroma_conversion_gain    0.299,0.587,0.114
chroma_a                  0.64,0.33
chroma_b                  0.30,0.60
chroma_c                  0.15,0.06
chroma_y_gain             0.2126,0.7152,0.0722

#
# NTSC POST-PROCESSING OPTIONS
#
yiq_enable                0
yiq_jitter                0.0
yiq_cc                    3.57954545
yiq_a                     0.5
yiq_b                     0.5
yiq_o                     0.0
yiq_p                     1.0
yiq_n                     1.0
yiq_y                     6.0
yiq_i                     1.2
yiq_q                     0.6
yiq_scan_time             52.6
yiq_phase_count           2

#
# VECTOR POST-PROCESSING OPTIONS
#
vector_beam_smooth        0.0
vector_length_scale       0.5
vector_length_ratio       0.5

#
# BLOOM POST-PROCESSING OPTIONS
#
bloom_blend_mode          0
bloom_scale               0.0
bloom_overdrive           1.0,1.0,1.0
bloom_lvl0_weight         1.0
bloom_lvl1_weight         0.64
bloom_lvl2_weight         0.32
bloom_lvl3_weight         0.16
bloom_lvl4_weight         0.08
bloom_lvl5_weight         0.06
bloom_lvl6_weight         0.04
bloom_lvl7_weight         0.02
bloom_lvl8_weight         0.01
lut_texture               lut-default.png
lut_enable                0
ui_lut_texture            lut-default.png
ui_lut_enable             0

#
# FULL SCREEN OPTIONS
#
triplebuffer              0
full_screen_brightness    1.0
full_screen_contrast      1.0
full_screen_gamma         1.0

#
# INPUT DEVICE OPTIONS
#
global_inputs             0
dual_lightgun             0
```

/Emulation/tools/MAME/neogeo.ini
```
#
# CORE CONFIGURATION OPTIONS
#
readconfig                1
writeconfig               0

bios                      16
```

/Emulation/tools/MAME/plugin.ini
```
#
# PLUGINS OPTIONS
#
autofire                  0
cheat                     0
cheatfind                 0
commonui                  0
console                   0
data                      1
discord                   0
dummy                     0
gdbstub                   0
hiscore                   1
inputmacro                0
json                      0
layout                    0
portname                  0
timecode                  0
timer                     0
SLAXML                    0
```

/Emulation/tools/MAME/ui.ini
```
#
# UI SEARCH PATH OPTIONS
#
historypath               history;dats;.
categorypath              folders
cabinets_directory        cabinets;cabdevs
cpanels_directory         cpanel
pcbs_directory            pcb
flyers_directory          flyers
titles_directory          titles
ends_directory            ends
marquees_directory        marquees
artwork_preview_directory "artwork preview;artpreview"
bosses_directory          bosses
logos_directory           logo
scores_directory          scores
versus_directory          versus
gameover_directory        gameover
howto_directory           howto
select_directory          select
icons_directory           icons
covers_directory          covers
ui_path                   ui

#
# UI MISC OPTIONS
#
system_names              
skip_warnings             0
remember_last             1
enlarge_snaps             1
forced4x3                 1
use_background            1
skip_biosmenu             1
skip_partsmenu            0
last_used_filter          Available
last_right_panel          1
last_used_machine         
info_audit_enabled        0
hide_romless              1
unthrottle_mute           0

#
# UI OPTIONS
#
infos_text_size           1.000000
font_rows                 30
hide_main_panel           0
ui_border_color           ffffffff
ui_bg_color               ef101030
ui_clone_color            ff808080
ui_dipsw_color            ffffff00
ui_gfxviewer_color        ef101030
ui_mousedown_bg_color     b0606000
ui_mousedown_color        ffffff80
ui_mouseover_bg_color     70404000
ui_mouseover_color        ffffff80
ui_selected_bg_color      ef808000
ui_selected_color         ffffff00
ui_slider_color           ffffffff
ui_subitem_color          ffffffff
ui_text_bg_color          ef000000
ui_text_color             ffffffff
ui_unavail_color          ff404040
```

**Comment by Godsbane** [comment]
I want to move the install to /Emulation/emulators/mame/ so the actual program would go there.
I have some plans on doing more things in Emulation/emulators so i think it makes sense.

**Comment by drewbaumann** [comment]
Whats the status of this PR? I recently set up EmuDeck and had trouble getting a couple MAME games to work. Would be stoked to see that change for users of this awesome project. Let me know if there is anything I can do to help.

**Comment by Godsbane** [comment]
It's on hold. There's a native MAME flatpak coming to flathub soon.

**Comment by Godsbane** [comment]
closing as mame flatpak support is complete

**Pull request closed without merging**
