### PR TITLE
cleanup SRM

### PR DESCRIPTION
**Pull request by WingofaGriffin**
Mostly alphabetizing.

Disabled Cloud Services by default as it was causing many errors for users who didn't have it configured.

Disabled RA Mupen in favor of RMG as I am inclined to believe that it runs better, but feel free to change back.

mGBA not touched as it was disabled by default

### CODE REVIEW

**Comment by WingofaGriffin** [comment]
Also adding tic80 and swapped yabuase to kronos

**Comment by Godsbane** [comment]
The defaults shouldn't change. They need to align with easy mode.

I did fix the cloud parser, so it should stay enabled.

If you want to alphabetize it still, i am down though!

**Comment by Godsbane** [comment]
@WingofaGriffin we may need to readdress this PR a second time, as Steam's beta client no longer seems to work with arguments appended to the executable field.

**Comment by WingofaGriffin** [comment]
Yabuase isn't a default, Beetle is. Kronos is just updated Yabuase as Yabuase is abandon-ware. It does perform better and using more modern APIs.

**Comment by WingofaGriffin** [comment]
Closing due to new SRM handling

**Pull request closed without merging**
