### PR TITLE
Fix #291 - Windows Path issue

### LINKED ISSUE #291: Cemu Path logic error
https://github.com/dragoonDorise/EmuDeck/blob/main/install.sh#L900

They need to be back slashes or else CEMU doesn't load the roms, you are adding forward slashes

Example output should look like this:
```
<GamePaths>
        <Entry>Z:\run\media\mmcblk0p1\Emulation\roms\wiiu\roms</Entry>
</GamePaths>
```

not 

```
<GamePaths>
        <Entry>Z:/run/media/mmcblk0p1/Emulation/roms/wiiu/roms</Entry>
</GamePaths>
```

### PR DESCRIPTION
**Pull request by james2432**
Fixing the windows path issue described in #291

### CODE REVIEW

**Comment by Godsbane** [comment]
every time that runs, it will add another entry because the string maniuplation is after the string gets searched for.

**Review by Godsbane — CHANGES_REQUESTED** [review]
move the windows path variable creation above the search. Use the variable in the grep.

**Comment by james2432** [comment]
Fixed

**Review by Godsbane — APPROVED** [review]
Looks good to me

**Comment by james2432** [comment]
👍

**Pull request merged**
