### PR TITLE
Emu reorg linting

### PR DESCRIPTION
**Pull request by DylanTackoor**
This pr fixes _some_ shell script lint errors.

- Fixes some shellcheck errors, mostly just some [double quotes fixes](https://www.shellcheck.net/wiki/SC2086) and swapping most instances of `~` with `$HOME`
- Formats shell scripts with [shfmt](https://github.com/patrickvane/shfmt) (not actually checked in my other PR yet but i'll get to that when I get to eslint)
- Arbitrarily standardized all shell scripts to a indentation size of 2 tabs and added newlines after each shebang

I just kinda figured `EmuReorg` would be the best place to start fixing lint stuff, but if not I could submit another PR into `dev`

### CODE REVIEW

**Comment by DylanTackoor** [comment]
i'll uh, resolve those conflicts if someone says these changes look cool

**Comment by DylanTackoor** [comment]
actually wasn't too bad to resolves the conflicts 😄

**Comment by Godsbane** [comment]
how mad are you going to be when i go through and redo a bunch of this before merging so i can test lol

**Comment by DylanTackoor** [comment]
it's cool if this PR is just closed lol, wouldn't take me very long to redo it :)

**Comment by Godsbane** [comment]
yeah unfortunately, this is just not ready yet. Trying to make this code more manageable. (like faux object oriented, etc)

**Comment by DylanTackoor** [comment]
cool no worries I'll redo this later, figured it was a gamble as it's not the dev branch. The refactoring looks nice from what I've read though at least 😄

**Pull request closed without merging**
