### PR TITLE
Switch Citra from Flatpak install to Appimage

### PR DESCRIPTION
**Pull request by Efadd**

### CODE REVIEW

**Comment by dragoonDorise** [comment]
@Efadd also, the PR go to the DEV branch :)

**Comment by SilentException** [comment]
I would argue that switching from FP to AI has it's pros and cons.
Is there a specific reason this should be migrated at this point? Citra flatpak seems to be maintained properly.

**Comment by Efadd** [comment]
Silent, the flatpak is known to have issues with Pokemon rn, and we more directly maintain the AppImage rather than shipping our source code out for someone else to build. And rn it has issues with Pokemon, and we're planning on deprecating FP at some point anyways

Also, with Appimage and our install script the option is there to install Canary later.

**Comment by Efadd** [comment]
I never touched those files......

Unless this is dev vs main issues, cause I forked main

**Comment by SilentException** [comment]
Cool, I didn't realize at first you're on Citra Discord. We talked about this a week ago. I was actually suggesting Citra to put Canary version on flathub-beta repo ;)

If that's the route Citra is going then I see no problem with the switch. 

One of the benefits of flatpak is that it is possible to set up and use mesa-git just by setting environment variable. Updated drivers help in some cases while waiting for Valve to ship them with SteamOS update..not sure how AppImage handles that.

**Comment by Godsbane** [comment]
@Efadd can you please rebase your changes on Dev? I'll get it merged for testing.

**Comment by Efadd** [comment]
> @Efadd can you please rebase your changes on Dev? I'll get it merged for testing.

I would if I knew how....... should I refork from dev and copy my Citra edits there?

**Comment by Godsbane** [comment]
Yes i think that would be best. If you want to do that, then PR to Dev again we can merge after.

**Comment by Efadd** [comment]
Going to re-fork from Dev instead of Main

**Pull request closed without merging**
