### PR TITLE
Add pCloud and Mega as Providers

### PR DESCRIPTION
**Pull request by WingofaGriffin**
Given the feature isn't fully done yet, I figured I'd add these two to the mix as options. I know this is a @dragoonDorise project so feel free to take what you want.

### CODE REVIEW

**Comment by Godsbane** [comment]
Not having used these two - any special fields need to be implemented? does it work as is with just these changes?

**Comment by WingofaGriffin** [comment]
These were based directly on the rclone examples on the official website. There isn't any code here to generate the tokens and auth, but they weren't there on the other providers too, making me assume that it's stored in another repo and needs to be updated there.

**Comment by Godsbane** [comment]
any special setup goes in 

rclone_updateProvider. The only special one atm is the one for nextcloud.

Going to need special form input for the local sync one too; and sftp. so if any special settings need to go in the file, that's where it's done :)

**Comment by WingofaGriffin** [comment]
Hm interesting, as it seems to only ask for username and password, when most use auth tokens. Will check out a bit

**Comment by WingofaGriffin** [comment]
For reference:
pCloud https://rclone.org/pcloud/
Mega https://rclone.org/mega/

**Comment by dragoonDorise** [comment]
@WingofaGriffin @Godsbane  already working on this on #745

**Comment by dragoonDorise** [comment]
@WingofaGriffin closing this as we already have in on my PR. I'm not so sure about using Mega, in the rclone doc talks about issues with duplicates because Mega allows you to have duplicated files with the same name so I'm gonna sit that one out for now.

**Pull request closed without merging**
