### PR TITLE
Supermodel Sega Model 3 Emulator

### PR DESCRIPTION
**Pull request by WingofaGriffin**
- [x] supermodel.sh
- [x] emudecksupermodel.sh
- [x] all.sh
- [x] setup.sh
- [x] installCLI.sh
- [x] settings.sh
- [x] uninstall.sh
- [x] helperFunctions.sh
- [x] SRM Parser
- [x] Configs

### CODE REVIEW

**Comment by dragoonDorise** [comment]
@WingofaGriffin I ❤️ this PR

**Comment by WingofaGriffin** [comment]
> For the configs:
> 
> ```
> mkdir -p $HOME/.supermodel/Analysis $HOME/.supermodel/Log $HOME/.supermodel/NVRAM
> cp -r $HOME/.local/share/flatpak/app/com.supermodel3.Supermodel/current/active/files/bin/Config $HOME/.supermodel
> cp -r $HOME/.local/share/flatpak/app/com.supermodel3.Supermodel/current/active/files/bin/Assets $HOME/.supermodel
> cp -r $HOME/.local/share/flatpak/app/com.supermodel3.Supermodel/current/active/files/bin/Docs $HOME/.supermodel
> ```
> 
> Can download/use the config from: https://forums.launchbox-app.com/files/file/3926-sega-model-2-emulator-everything-pre-configured-inc-controls-for-pc-controller-mouse-light-guns-test-menus-configured-analogue-inputs-calibrated-free-play-all-games-in-english-2-player-mouse-support-no-screen-flash/ as a reference.

Is there a reason this is a cp and not a symlink?

**Comment by WingofaGriffin** [comment]
Blocked on bad flatpak. See https://github.com/flathub/com.supermodel3.Supermodel/issues/1

**Comment by WingofaGriffin** [comment]
> `rsync -avhp --mkpath "$Supermodel_gamesList" "$HOME/.supermodel/Config" --backup --suffix=.bak`
> 
> When running this, I get the below error:
> 
> sent 920 bytes received 15 bytes 1.87K bytes/sec total size is 4.57M speedup is 4,886.62 ssh: Could not resolve hostname https: Name or service not known rsync error: unexplained error (code 255) at log.c(245) [Receiver=3.2.7] NYI NYI NYI

Yeah I'm dumb and used rsync when I should have used wget. Try again now?

**Comment by dragoonDorise** [comment]
@WingofaGriffin is this ready to be merged? :)

**Comment by WingofaGriffin** [comment]
> @WingofaGriffin is this ready to be merged? :)

I believe so!

**Review by dragoonDorise — APPROVED** [review]

**Pull request merged**
