### PR TITLE
binupdate improvements

### PR DESCRIPTION
**Pull request by SilentException**
All because wrapping binupdate.sh _install methods in zenity progress dialog broke update of some emulators.
Needed to show download progress only while downloading. Changed (hopefully improved) some other things as well.

- new safeDownload() in helperFunctions
- introduced showProgress argument for emulator downloads
- modified binupdate.sh to use showProgress
- modified emulator/tools install functions to use safeDownload()/showProgress and return proper exit code (CemuNative, Cemu, mGBA, PCSX2-QT, Ryujinx, Vita3K, Xenia, Yuzu, ESDE, SRM)
- installEmuAI() and installEmuBI() are now using new safeDownload() and return proper exit code
- installEmuAI() and installEmuBI() can now write last version info (new arguments)
- yuzu launcher: Added ~/emudeck/yuzu.noupdate to skip yuzu update, zenity progress bar and zenity error dialog

### CODE REVIEW

**Comment by Godsbane** [comment]
Read through it quickly, and it's looking great.

Mark as ready for review and I will take a deeper dive.

Thanks.

**Comment by SilentException** [comment]
Hey @Godsbane, thanks for taking a peek. I wanted to go over the changes myself before marking it ready. Did some formatting changes and noticed an error in one script. Now I think it's ready.

**Comment by SilentException** [comment]
Thanks for accepting the PR and fixing the yuzu launcher. I was hyper focused on binupdate and forgot to actually go through yuzu update at least once :)

**Comment by Godsbane** [comment]
np - it's awesome work. much appreciated.

**Pull request merged**
