### PR TITLE
Add cloud services

### PR DESCRIPTION
**Pull request by KingIzzymon**
This is in response to (Issue #144: Streaming Gaming Services) 
* Added cloud services parser in SRM config.
* Added scripts with matching SteamGridDB names for proper scraping.
* Added cloudServicesManager.sh

cloudServicesManager Features: 
* Auto-update cloud services list based on github repo.
* Updates exsisting scripts without touching user custom added scripts (based on file name).
* Edit `cloud.conf` file to change default web browser for scripts.

Extra: One script can run in the background (i.e. Spotify) while playing a non-cloud game

Note: Scripts require Google Chrome, Microsoft Edge or Mozilla Firefox flatpak to be installed.

### CODE REVIEW

**Comment by Godsbane** [comment]
Looking good to me so far.

What are your thoughts on how these get moved from tools to the roms folder? Just let the user pick manually? Make a script with a Zenity script to move them in? (perhaps checkboxes or something, to "Install" them?)

**Comment by KingIzzymon** [comment]
Agreed, the more user friendly the better. Not everyone's a techy lol Did u wanna work on it or should I? I just haven't used Zenity before but always open to learning something new.

**Comment by Godsbane** [comment]
Please absolutely feel free. If you get stuck let me know. You can also join the discord if you have questions, and i'm happy to help.

**Comment by KingIzzymon** [comment]
Sounds good. I'll take a whack at it tonight :)

**Comment by KingIzzymon** [comment]
@Godsbane All done. Please take a look and let me know what you think. For dev, you need to edit the github url and branch variables at the top of the cloudServicesManager script.

**Comment by Godsbane** [comment]
At first glance it looks good. I'll merge this into the feature branch and we can do some tests / iterate / add remote gaming.

**Pull request merged**
