### PR TITLE
Fix SD Card detection and references to mmcblk0p1

### PR DESCRIPTION
**Pull request by Godsbane**
fixes: #29

### CODE REVIEW

**Comment by Godsbane** [comment]
config files still have references to mmcblk0p1

**Comment by dragoonDorise** [comment]
Hi, just found one issue with this, when you mount the scared using /dev then you can no longer eject the SD card on desktop mode unless you type you user password. Any workaround to this before I deploy this to the main branch?

**Comment by Godsbane** [comment]
I don't know why checking the mount location would cause the pw to be required for ejection. Is it possible it's just a polkit bug?

**Comment by dragoonDorise** [comment]
I've found another issue when using non ext4 cards...the script can't create symlinks there, can you check if you can replicate the issue on your end?

**Comment by Godsbane** [comment]
Hey Dragoon - i'll test this, however, i want to point out the naming has nothing to do with ext4. mine is ext4, but named external and very happy  :)

**Pull request merged**
