### PR TITLE
Add New MAME Parsers

### PR DESCRIPTION
**Pull request by rawdatafeel**
Adds MAME core specific parsers:

* Philips CD-i - MAME
    * http://adb.arcadeitalia.net/?search=mess&machine_name=cdimono1%3B
    * BIOS: `cdimono1.zip`
* SNK Neo Geo CD - MAME
    * http://adb.arcadeitalia.net/?search=mess&machine_name=neocd%3Bneocdz%3Bneocdzj%3B
    * BIOS: `neocdz.zip`
* Tiger Electronics Game.com - MAME
    * http://adb.arcadeitalia.net/?search=mess&machine_name=gamecom%3B
    * BIOS: `gamecom.zip`
* VTech V.Smile - MAME
    * http://adb.arcadeitalia.net/?search=mess&machine_name=vsmile%3B
    * BIOS: `vsmile.zip`
  
For compatibility with both Steam ROM Manager and EmulationStation-DE, place BIOS files in respective ROM folder.

These parsers can be used as reference to add additional MAME specific cores to Steam ROM Manager in the future.

### CODE REVIEW

**Comment by WingofaGriffin** [comment]
Phillips CDi already exists with the samecdi core in RA (MAME based but more optimized) so I am not sure how relevant that one is https://github.com/dragoonDorise/EmuDeck/blob/beta/configs/steam-rom-manager/userData/userConfigurations.json#L4800

**Comment by dragoonDorise** [comment]
@rawdatafeel  parser parsers :)

**Comment by WingofaGriffin** [comment]
Should we add BBC micro to this too as discussed in discord?

**Comment by Godsbane** [comment]
I will merge this for now. You can do the bbc micro one on it's own if it gets figured out.

**Pull request merged**
