### PR TITLE
Readd keyboard hotkeys to yuzu

### LINKED ISSUE #494: Suggestion: EmuDeck hotkeys as additional rather than swapping default ones
In yuzu, for example, EmuDeck hotkeys layout completely swaps all the hotkeys, which causes troubles in Desktop Mode (i.e. cannot exit full-screen mode).
EmuDeck **should not change/remove default hotkeys** if possible.

EmuDeck controls:
EmuDeck controls

Default controls:
Default controls

### PR DESCRIPTION
**Pull request by exp111**
Should come out to this:
grafik

Closes #494 
(Doesn't add them as additional, but readds the keyboard shortcuts as the emudeck controller shortcuts should contain all we need and afaik yuzu doesn't support multiple hotkeys)

### CODE REVIEW

**Comment by Godsbane** [comment]
Do you want to update this to use the new guids from Yuzu too so i can merge it all in one go?

```
03000000de280000ff11000001000000 is the old GUID for ALL steam controllers - with different ports for controllers. (engine:sdl,port:2,guid:03000000de280000ff11000001000000 - for example)
Post 1261:
030079f6de280000ff11000001000000 is the GUID for steam controller (1)
0300b836de280000ff11000001000000 is the GUID for steam controller (2)
0300f837de280000ff11000001000000 is the GUID for steam controller (3)
030039f7de280000ff11000001000000 is the GUID for steam controller (4)
```

**Comment by Godsbane** [comment]
and one more change the Yuzu team asked us to make:
set CPU accuracy to auto.

**Comment by exp111** [comment]
I'll do that later today

**Comment by Godsbane** [comment]
Thank you. I will test, and then prob rebase ro prod for hotfix.

**Pull request merged**
