### PR TITLE
Create filesystem whitelist

### PR DESCRIPTION
**Pull request by Godsbane**
test the filesystem of the sd card against a whitelist instead of just ext4.
added in some logging for what we find during those tests.

### CODE REVIEW

**Comment by Witherking25** [comment]
Nice!

**Comment by Witherking25** [comment]
we can move fs discussion here

**Comment by Witherking25** [comment]
this should have a toggle in advanced settings

**Comment by Godsbane** [comment]
this is so out of sync i don't know what to do with it in git. i am going to close it, and remake this.

**Pull request closed without merging**
