### PR TITLE
Remove dependency on google

### PR DESCRIPTION
**Pull request by james2432**
- Remove dependency on google.
- Removed dependency on outbound port 53 being unblocked (many secure networks block this so DNS cannot be bypassed and have to resolve inside network)
- Test connection like it's about to be used (HTTPS connection to github)

### CODE REVIEW

**Comment by Godsbane** [comment]
I think your points are valid.

Do you think it's worth adding a second test if GitHub fails? EA for example, is not hosted on GitHub.

**Comment by james2432** [comment]
Updated the check to be in mainline or EA before it actually makes a connection, this way the test is only done once and only depends on what it's going to fetch (github or yuzu)

**Comment by WingofaGriffin** [comment]
Agree that this is probably a better way to go. I've been mostly using wget but a curl or even a ping should be more than fine.

**Comment by james2432** [comment]
it's only getting the headers for the page and testing for 2xx so if the webpage is erroring out, it won't download either(error 4xx 5xx)

**Pull request merged**
