### PR TITLE
Adds GitHub Actions linting

### PR DESCRIPTION
**Pull request by DylanTackoor**
Unsure if this is something this project wants, but I finally got some time to work on this and threw together some GitHub Actions CI jobs real quick.

Adds GHA lint jobs for:
- `.sh` with shellcheck & shfmt
- `.md` with markdownlint
- `.ps1` with PSScriptAnalyzer

I've got a [summary of a demo run here](https://github.com/DylanTackoor/EmuDeck/actions/runs/2480499236). Assuming some CI jobs like this are wanted, I could start fixing the shellscript lint errors and provide hosting for the GHA runners.

image

I'd also need to check if the powershell linting is actually working as I've only touched ps scripts once before 🙃

### CODE REVIEW

**Comment by DylanTackoor** [comment]
My initial version of these CI jobs use prefabbed github actions as it only took a few minutes, but if this is a worthwhile inclusion I could also move it to shell scripts inside the repo for local linting.

**Comment by Godsbane** [comment]
hey this is cool, will chat with dragoon, but i think this could be very handy.

**Comment by dragoonDorise** [comment]
Hi @DylanTackoor ,great work, thanks! Before merging the PR, do we need to do something else after? I'm totally new to GitHub actions

**Comment by DylanTackoor** [comment]
@dragoonDorise afaik you shouldn't need to change any github settings to enable this, iirc just merging the PR will get the CI jobs running [within the GHA free tier](https://github.com/pricing) on future PRs. They'll start to have [failed checks like in my test PR](https://github.com/DylanTackoor/EmuDeck/pull/5) until the lint errors are resolved, but you'll be able to merge anyway.

image

Before merging this PR, I should update the GHA config to also check stuff on the `beta` branch and check if the `toml-lint`+`shfmnt` jobs are really necessary

**Review by Godsbane — APPROVED** [review]
Looks good to me so far.
We'll need to add in JS for the next release, but it should be good to show us problematic code now.

**Pull request merged**
