### PR TITLE
Add emu-launch.sh

### PR DESCRIPTION
**Pull request by AngelofWoe**

### CODE REVIEW

**Comment by Godsbane** [comment]
Thanks @AngelofWoe - I rebased to dev and then I reviewed this, looks great - the only thing I'd ask at this point, is can you clean up the SRM stuff? I merged some other changes to DEV for building dual folder parsers, and then there's the removal of the DefaultTallImage images, and the addition of Sameboy.

We can merge to Dev after that.

**Comment by AngelofWoe** [comment]
Conflicts should be fixed

**Comment by AngelofWoe** [comment]
We probably want to switch to dev for this

**Comment by AngelofWoe** [comment]
Should be ready to merge.

**Pull request merged**
